### ISSUE TITLE
Still `QGuiApplicationPrivate::createPlatformIntegration()` crash when in standalone

### ISSUE THREAD

**Issue by arthurdouillard** [bootchk/qtLibPathFacade#1]
Hello,

Thanks for your fix, but i doesn't work for me, i still have `QGuiApplicationPrivate::createPlatformIntegration()` crash problem.

It seems that libcocoa.dylib doesn't want to be found. Here a code toy where it crash (when bundled with **py2app**):

```
QtLibPathFacade.addBundledPluginsPath()
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

def main():
    app = QtWidgets.QApplication(sys.argv)

    w = QtWidgets.QWidget()
    w.resize(250, 150)
    w.move(300, 300)
    w.setWindowTitle('Simple')
    w.show()

    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```

I don't want to disturb you about it, but if you have any idea, could you enlight me please ? :)

**Comment by bootchk** [comment]
Go ahead, disturb me.

You call the facade earlier than in the example in the README.  Did you try calling it as in the example, i.e. the first thing in main() ?

The facade writes the paths to syslog.  You can read that with the Apple  'Console' app.  That info might help debug.

Are you sure you sure you have built correctly?  When you sandbox an app, the libs get put in the bundle, in a directory 'Plugins'.  You can see the contents of your app bundle by clicking RMB (right mouse button) on the app bundle (on the icon) and choosing "Show Package Contents" from the context menu.

Just ideas, hard to debug without more information.

**Comment by bootchk** [comment]
Also, I assume it is just a typo, but I think the lib name is libqcocoa (i.e. there is a 'q' in it.)  And that's probably irrelevant.

**Comment by arthurdouillard** [comment]
I've tried calling the facade like the example:

```
def main():
    QtLibPathFacade.addBundledPluginsPath()
    app = QtWidgets.QApplication(sys.argv)
```

It doesn't change anything.
However after looking the console i got some infos that may seem useful:

`26/01/16 14:24:28,641 /test.py[7453]: appDirPath: /Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/MacOS`
`26/01/16 14:24:28,642 /test.py[7453]: Could not cd to PlugIns`
`26/01/16 14:24:28,642 /test.py[7453]: pluginDirPath: None`

It seems that it cannot find **path to plugins**, do you know how could i 'force' him to find it ?
Thank you for your help :)

**Comment by bootchk** [comment]
Are you sure the directory exists?  Same level as MacOS directory.  (Look at the code, it tries to change directory up from MacOS, then change directory down into PlugIns.  It is failing to change directory down into PlugIns.)

/Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/MacOS
/Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/PlugIns/libqcocoa.dylib

In other words, are you sure your build process has the step of copying  libqcocoa.dylib into the PlugIns directory of the bundle?  You might need to configure that step manually  (I don't use py2app, I used pyqtdeploy.)

**Comment by arthurdouillard** [comment]
I've tried to copy manually libqcocoa.dylib in the path you gave: 
`dist/test.app/Contents/PlugIns/libqcocoa.dylib`

However it still crash with the same QT error, but the log changed:
`26/01/16 17:27:58,464 /test.py[7581]: appDirPath: /Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/MacOS`
`26/01/16 17:27:58,465 /test.py[7581]: pluginDirPath: /Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/PlugIns`
`26/01/16 17:27:58,465 /test.py[7581]: On MacOS, prepending plugin path: /Users/arthur/code/quick_test/test_qt/dist/test.app/Contents/PlugIns`

It seems like my `libqcocoadylib` is the problem ? It's a copy of the one from Qt5 plugins platform folder...

Thank you for your help :)

**Comment by bootchk** [comment]
At this point, you need more information.  Can you start the app in the debugger (e.g. gdb) and when it crashes, get a backtrace (debugger  command is 'bt' ).  That will tell you what the call stack was when it crashed.  Then you might be able to tell if it crashed in the library, or somewhere else.

I assume you are compiling and building from the command line.  The learning curve is steep, but you might consider using Xcode,  because, possibly you are missing some vital build step that Xcode would more or less automate.

**Comment by arthurdouillard** [comment]
Yep i know gdb, i've used it several times for C&C++, but i can't manage to add debug flag to the bundled app.

I'll consider Xcode (i kind of like stay in my cosy shell); but i think i'll just rage quit this problem. I've been on it for 2 weeks using every methods found on the web and reinstalling twice everything.

But thank you for your help, it has been apreciated. :)
